name: Sync Upstream

on:
  schedule:
    - cron: '0 2 * * *'      # 每天凌晨 2 点 UTC
  workflow_dispatch:          # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Squidly271/AppFeed.git

      - name: Detect default branch
        id: default
        run: |
          git fetch upstream
          DEFAULT_BRANCH=$(git remote show upstream | awk '/HEAD branch/ {print $NF}')
          echo "branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

      - name: Sync with upstream
        run: |
          git checkout ${{ steps.default.outputs.branch }}
          git merge upstream/${{ steps.default.outputs.branch }} --allow-unrelated-histories --no-edit
          git push origin ${{ steps.default.outputs.branch }}
