name: Auto-sync upstream (AppFeed)

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 02:00 UTC
  workflow_dispatch:        # 也可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name  'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Squidly271/AppFeed.git

      - name: Detect default branch
        id: branch
        run: |
          git fetch upstream
          DEFAULT=$(git remote show upstream | awk '/HEAD branch/ {print $NF}')
          echo "branch=$DEFAULT" >> $GITHUB_OUTPUT

      - name: Sync with upstream
        run: |
          git checkout ${{ steps.branch.outputs.branch }}
          git merge upstream/${{ steps.branch.outputs.branch }} --allow-unrelated-histories --no-edit
          git push origin ${{ steps.branch.outputs.branch }}
